// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMV4opedzpj3XFdaG_rzONYYoaRQ3GGU8',
    appId: '1:180600679119:web:f59ff2a741f17f513765ba',
    messagingSenderId: '180600679119',
    projectId: 'foodgo-e27b0',
    authDomain: 'foodgo-e27b0.firebaseapp.com',
    storageBucket: 'foodgo-e27b0.firebasestorage.app',
    measurementId: 'G-062KJL9B6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk178zwG2nyHHTSXQzr0RUJeHlFejK008',
    appId: '1:180600679119:android:2426d7519de13df03765ba',
    messagingSenderId: '180600679119',
    projectId: 'foodgo-e27b0',
    storageBucket: 'foodgo-e27b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq39sedY47kJJIS_KSeucgHtvyOaJCeBg',
    appId: '1:180600679119:ios:54076cd5a43dbde13765ba',
    messagingSenderId: '180600679119',
    projectId: 'foodgo-e27b0',
    storageBucket: 'foodgo-e27b0.firebasestorage.app',
    iosBundleId: 'com.example.foodgo',
  );
}
